apiVersion: v1
kind: ConfigMap
metadata:
  name: coe-config-kafka
data:
  lstreamd_default.conf: |
    { 
        "Endpoints": {
          "KAFKA": {
            "ServerUrl": "X.X.X.X:9092",
            "KafkaTopic": "HTTP",
            "DataFormat": "AVRO",
            "RecordType": {
                "HTTP": "all",
                "TCP": "all",
                "SWG": "all",
                "VPN": "all",
                "NGS": "all",
                "ICA": "all",
                "APPFW": "none",
                "BOT": "none",
                "VIDEOOPT": "none",
                "BURST_CQA": "none",
                "SLA": "none",
                "MONGO": "none"
            },
            "TimeSeries": {
                "EVENTS": "no",
                "AUDITLOGS": "no"
            },
            "ProcessAlways": "yes",
            "FileSizeMax": "40",
            "ProcessYieldTimeOut": "500",
            "FileStorageLimit": "1000",
            "SkipAvro": "no",
            "AvroCompress": "yes"
          }
       }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coe-kafka
  labels: 
    app: coe-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coe-kafka
  template:
    metadata:
      name: coe-kafka
      labels:
        app: coe-kafka
    spec:
      hostAliases:
        - ip: "X.X.X.X"
          hostnames:
            - "kafka-node1"
        - ip: "Y.Y.Y.Y"
          hostnames:
            - "kafka-node2"
        - ip: "Z.Z.Z.Z"
          hostnames:
            - "kafka-node3"
      containers:
        - name: coe-kafka
          image: "quay.io/citrix/citrix-observability-exporter:1.9.001"
          imagePullPolicy: Always
          ports:
            - containerPort: 5557
              name: lstream
          volumeMounts:
            - name: lstreamd-config-kafka
              mountPath: /var/logproxy/lstreamd/conf/lstreamd_default.conf
              subPath: lstreamd_default.conf
            - name: core-data
              mountPath: /var/crash/
          env:
            - name: NSOE_LOG_LEVEL
              value: "INFO"
      volumes:
        - name: lstreamd-config-kafka
          configMap:
            name: coe-config-kafka
        - name: core-data
          emptyDir: {}
---
# Citrix-observability-exporter headless service  
apiVersion: v1
kind: Service
metadata:
  name: coe-kafka
  labels:
    app: coe-kafka
spec:
  clusterIP: None
  ports:
    - port: 5557
      protocol: TCP
  selector:
      app: coe-kafka
---
# Citrix-observability-exporter NodePort service
apiVersion: v1
kind: Service
metadata:
  name: coe-kafka-nodeport
  labels:
    app: coe-kafka
spec:
  type: NodePort
  ports:
    - port: 5557
      protocol: TCP
  selector: 
      app: coe-kafka
